const cars = [
  {
    producer: "Toyota",
    year_of_production: 2018,
    model: "Camry",
    horse_power: 203,
    mileage_km: 50000,
    extras: [
      "nawigacja GPS",
      "podgrzewane fotele",
      "system audio premium",
      "dach panoramiczny",
    ],
  },
  {
    producer: "Honda",
    year_of_production: 2019,
    model: "Civic",
    horse_power: 158,
    mileage_km: 40000,
    extras: [
      "kamera cofania",
      "system bezpieczeństwa Honda Sensing",
      "ładowarka indukcyjna do telefonu",
      "skórzane tapicerki",
    ],
  },
  {
    producer: "Ford",
    year_of_production: 2017,
    model: "Focus",
    horse_power: 160,
    mileage_km: 60000,
    extras: [
      "klimatyzacja dwustrefowa",
      "system rozpoznawania znaków drogowych",
      "asystent parkowania",
      "podgrzewane lusterka boczne",
    ],
  },
  {
    producer: "Chevrolet",
    year_of_production: 2016,
    model: "Malibu",
    horse_power: 160,
    mileage_km: 70000,
    extras: [
      "skórzane fotele",
      "szyberdach",
      "system audio Bose",
      "nawigacja GPS",
    ],
  },
  {
    producer: "Nissan",
    year_of_production: 2019,
    model: "Altima",
    horse_power: 188,
    mileage_km: 35000,
    extras: [
      "klimatyzacja automatyczna",
      "system multimedialny z ekranem dotykowym",
      "łopatki zmiany biegów przy kierownicy",
      "skórzane fotele",
    ],
  },
  {
    producer: "BMW",
    year_of_production: 2020,
    model: "3 Series",
    horse_power: 255,
    mileage_km: 20000,
    extras: [
      "pakiet M Sport",
      "klimatyzacja czterostrefowa",
      "system nagłośnienia Harman Kardon",
      "wyświetlacz HUD",
    ],
  },
  {
    producer: "Audi",
    year_of_production: 2018,
    model: "A4",
    horse_power: 248,
    mileage_km: 45000,
    extras: [
      "quattro - system napędu na cztery koła",
      "adaptacyjny tempomat z asystentem korkowym",
      "panoramiczny dach szklany",
      "fotele przednie sportowe",
    ],
  },
  {
    producer: "Mercedes-Benz",
    year_of_production: 2017,
    model: "C-Class",
    horse_power: 241,
    mileage_km: 55000,
    extras: [
      "pakiet AMG Line",
      "system komunikacji Car-to-X",
      "fotele komfortowe z funkcją masażu",
      "system nagłośnienia Burmester",
    ],
  },
  {
    producer: "Volkswagen",
    year_of_production: 2018,
    model: "Passat",
    horse_power: 174,
    mileage_km: 40000,
    extras: [
      "system audio Dynaudio",
      "wyświetlacz cyfrowy Active Info Display",
      "dynamiczne światła LED",
      "system asystenta parkowania Park Assist",
    ],
  },
  {
    producer: "Hyundai",
    year_of_production: 2019,
    model: "Elantra",
    horse_power: 147,
    mileage_km: 30000,
    extras: [
      "bezkluczykowy dostęp i rozruch",
      "system multimedialny z ekranem dotykowym 10,25 cala",
      "asystent pasa ruchu",
      "aktywny tempomat z funkcją Stop&Go",
    ],
  },
  {
    producer: "Kia",
    year_of_production: 2017,
    model: "Optima",
    horse_power: 185,
    mileage_km: 65000,
    extras: [
      "kamera 360 stopni",
      "system monitorowania martwego pola BSM",
      "system monitorowania tylnej kanapy",
      "elektryczne tylne szyby rolowane",
    ],
  },
  {
    producer: "Subaru",
    year_of_production: 2018,
    model: "Impreza",
    horse_power: 152,
    mileage_km: 55000,
    extras: [
      "system EyeSight z asystentem hamowania prekursorem",
      "system multimedialny z ekranem dotykowym 8 cali",
      "nawigacja GPS",
      "adaptacyjne światła przednie",
    ],
  },
  {
    producer: "Mazda",
    year_of_production: 2017,
    model: "Mazda3",
    horse_power: 155,
    mileage_km: 60000,
    extras: [
      "system bezpieczeństwa i-Activsense",
      "fotele przednie z funkcją ogrzewania",
      "system audio Bose",
      "nawigacja GPS",
    ],
  },
  {
    producer: "Lexus",
    year_of_production: 2019,
    model: "IS",
    horse_power: 241,
    mileage_km: 35000,
    extras: [
      "system nagłośnienia Mark Levinson",
      "fotele przednie z wentylacją",
      "system detekcji pieszych",
      "aktywny system stabilizacji toru jazdy",
    ],
  },
  {
    producer: "Infiniti",
    year_of_production: 2016,
    model: "Q50",
    horse_power: 208,
    mileage_km: 70000,
    extras: [
      "kamera 360 stopni",
      "system nagłośnienia Bose Performance Series",
      "adaptacyjny tempomat inteligentny",
      "system kontroli trakcji",
    ],
  },
  {
    producer: "Acura",
    year_of_production: 2018,
    model: "ILX",
    horse_power: 201,
    mileage_km: 50000,
    extras: [
      "klimatyzacja automatyczna dwustrefowa",
      "system nagłośnienia ELS Studio Premium Audio",
      "skórzane fotele",
      "system ostrzegania przed kolizją z funkcją automatycznego hamowania",
    ],
  },
  {
    producer: "Tesla",
    year_of_production: 2020,
    model: "Model 3",
    horse_power: 283,
    mileage_km: 15000,
    extras: [
      "pełne wykonanie wnętrza z ekologicznych materiałów",
      "autopilot z funkcją samojezdności",
      "dostęp do Superchargerów Tesla",
      "system audio High Fidelity",
    ],
  },
  {
    producer: "Volvo",
    year_of_production: 2017,
    model: "S60",
    horse_power: 250,
    mileage_km: 60000,
    extras: [
      "system City Safety z funkcją wykrywania zwierząt",
      "szyby przednie i tylne z podwójnym laminatem",
      "fotele przednie z funkcją masażu",
      "szyberdach panoramiczny",
    ],
  },
  {
    producer: "Toyota",
    year_of_production: 2019,
    model: "Corolla",
    horse_power: 132,
    mileage_km: 40000,
    extras: [
      "system Toyota Safety Sense",
      "fotele przednie sportowe",
      "nawigacja GPS",
      "dach panoramiczny",
    ],
  },
  {
    producer: "Honda",
    year_of_production: 2018,
    model: "Accord",
    horse_power: 192,
    mileage_km: 45000,
    extras: [
      "system nagłośnienia premium z 10 głośnikami",
      "nawigacja satelitarna Honda Satellite-Linked Navigation System",
      "wielofunkcyjny system kamer",
      "fotele przednie z funkcją masażu",
    ],
  },
  {
    producer: "Ford",
    year_of_production: 2019,
    model: "Fusion",
    horse_power: 175,
    mileage_km: 30000,
    extras: [
      "kamera cofania",
      "system audio Sony z 12 głośnikami",
      "system rozpoznawania znaków drogowych",
      "nawigacja GPS",
    ],
  },
  {
    producer: "Chevrolet",
    year_of_production: 2017,
    model: "Cruze",
    horse_power: 153,
    mileage_km: 55000,
    extras: [
      "system Chevrolet Infotainment 3 Plus",
      "fotele przednie z funkcją wentylacji",
      "system detekcji martwego pola",
      "asystent pasa ruchu",
    ],
  },
  {
    producer: "Nissan",
    year_of_production: 2018,
    model: "Maxima",
    horse_power: 300,
    mileage_km: 35000,
    extras: [
      "skórzane fotele",
      "szyberdach",
      "system audio Bose",
      "nawigacja GPS",
    ],
  },
  {
    producer: "BMW",
    year_of_production: 2017,
    model: "5 Series",
    horse_power: 248,
    mileage_km: 50000,
    extras: [
      "wyświetlacz Head-Up",
      "aktywny tempomat z funkcją Stop&Go",
      "asystent parkowania",
      "system multimedialny BMW Professional",
    ],
  },
  {
    producer: "Audi",
    year_of_production: 2019,
    model: "A6",
    horse_power: 335,
    mileage_km: 25000,
    extras: [
      "fotele przednie sportowe S line",
      "system Audi Virtual Cockpit",
      "reflektory Audi Matrix LED",
      "system nawigacji MMI Navigation plus z MMI touch",
    ],
  },
  {
    producer: "Mercedes-Benz",
    year_of_production: 2018,
    model: "E-Class",
    horse_power: 362,
    mileage_km: 20000,
    extras: [
      "pakiet AMG Line",
      "system multimedialny COMAND Online",
      "fotele komfortowe z funkcją masażu",
      "system multibeam LED",
    ],
  },
  {
    producer: "Volkswagen",
    year_of_production: 2019,
    model: "Jetta",
    horse_power: 147,
    mileage_km: 40000,
    extras: [
      "system audio BeatsAudio",
      "klimatyzacja automatyczna dwustrefowa",
      "wyświetlacz Active Info Display",
      "system nawigacji satelitarnej Discover Media",
    ],
  },
  {
    producer: "Hyundai",
    year_of_production: 2016,
    model: "Sonata",
    horse_power: 185,
    mileage_km: 70000,
    extras: [
      "system nawigacji z ekranem dotykowym 8 cali",
      "fotele przednie z funkcją wentylacji",
      "system bezpieczeństwa Hyundai SmartSense",
      "podgrzewane tylne siedzenia",
    ],
  },
  {
    producer: "Kia",
    year_of_production: 2018,
    model: "Forte",
    horse_power: 147,
    mileage_km: 50000,
    extras: [
      "system Kia UVO Link z ekranem dotykowym 8 cali",
      "ładowarka bezprzewodowa dla smartfonów",
      "asystent utrzymania pasa ruchu",
      "system monitorowania martwego pola",
    ],
  },
  {
    producer: "Subaru",
    year_of_production: 2020,
    model: "Legacy",
    horse_power: 182,
    mileage_km: 30000,
    extras: [
      "system EyeSight Driver Assist Technology",
      "fotele przednie z funkcją wentylacji",
      "system multimedialny z ekranem dotykowym 11,6 cala",
      "system audio Harman Kardon",
    ],
  },
  {
    producer: "Mazda",
    year_of_production: 2019,
    model: "Mazda6",
    horse_power: 187,
    mileage_km: 45000,
    extras: [
      "system nagłośnienia Bose",
      "wielofunkcyjny system kamer",
      "nawigacja satelitarna",
      "fotele przednie z funkcją masażu",
    ],
  },
  {
    producer: "Lexus",
    year_of_production: 2017,
    model: "RX",
    horse_power: 295,
    mileage_km: 55000,
    extras: [
      "pakiet Executive",
      "system multimedialny z ekranem dotykowym 12,3 cala",
      "fotele przednie z funkcją wentylacji",
      "dach panoramiczny",
    ],
  },
  {
    producer: "Infiniti",
    year_of_production: 2019,
    model: "Q60",
    horse_power: 300,
    mileage_km: 35000,
    extras: [
      "system Infiniti InTouch z ekranem dotykowym 8 cali",
      "system audio Bose Performance Series",
      "system nawigacji satelitarnej",
      "fotele przednie sportowe",
    ],
  },
  {
    producer: "Acura",
    year_of_production: 2017,
    model: "TLX",
    horse_power: 206,
    mileage_km: 40000,
    extras: [
      "system nagłośnienia ELS Studio Premium Audio",
      "system bezpieczeństwa AcuraWatch",
      "szyberdach",
      "system wykrywania zmęczenia kierowcy",
    ],
  },
  {
    producer: "Tesla",
    year_of_production: 2018,
    model: "Model S",
    horse_power: 503,
    mileage_km: 20000,
    extras: [
      "autopilot z funkcją Traffic-Aware Cruise Control",
      "pełne wykonanie wnętrza z naturalnych materiałów",
      "fotele przednie z funkcją masażu",
      "nawigacja GPS z wizualizacją terenu",
    ],
  },
  {
    producer: "Volvo",
    year_of_production: 2016,
    model: "XC60",
    horse_power: 250,
    mileage_km: 60000,
    extras: [
      "pakiet Inscription",
      "system multimedialny Sensus Connect",
      "klimatyzacja czterostrefowa",
      "szyberdach panoramiczny",
    ],
  },
];

export default cars;
